name: ESOGCBFMPC
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cyipopt=1.6.1
  - pip
  - pip:
      - flax==0.10.7
      - jax==0.6.2
      - jraph==0.0.6.dev0
      - jaxtyping==0.3.2
      - numpy==2.2.6
      - einops==0.8.1
      - matplotlib==3.9.2
      - opencv-python==4.11.0.86
      - tqdm==4.67.1
      - tensorflow-probability==0.25.0
      - optax==0.2.4
      - scipy==1.15.3
      - wandb==0.19.11
      - PyYAML==6.0.2
      - orbax-checkpoint==0.11.25
      - seaborn==0.13.2
      - equinox==0.13.1
      - loguru==0.7.3
      - attrs==24.2.0
      - rich==14.0.0
      - ipdb==0.13.13
      - colour==0.1.5
      - control==0.10.1
      - jaxproxqp @ git+https://github.com/oswinso/jaxproxqp.git@8b6d76028ef19642b9684a33584624295ea69128
      - pandas==2.2.3
      - psutil==6.1.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - cvxpy==1.6.6
      - clarabel==0.11.1
      - osqp==1.0.4
      - scs==3.2.7.post2












